# Настройки мониторинга
app_url: "http://127.0.0.1:5000"   # URL вашего приложения
check_interval: 10                 # Проверка каждые N секунд
timeout: 5                         # Таймаут запроса в секундах